version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
      - aws cloudformation package --template-file template_mvn.yml --s3-bucket url-shorten-lambda-code-build --output-template-file outputtemplate.yml
artifacts:
    files:
      - target/url-shortener-in-aws-lambda-1.0-SNAPSHOT-shaded.jar
      - template_mvn.yml
      - outputtemplate.yml
    discard-paths: yes