version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - aws cloudformation package --template-file template_mvn.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
      - mvn package
artifacts:
    files:
      - target/url-shortener-in-aws-1.1-SNAPSHOT.jar
      - template_mvn.yml
      - outputtemplate.yml
    discard-paths: yes