AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application which provides url-shortening function.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: url-shorten
      CodeUri: target/url-shortener-in-aws-lambda-1.0-SNAPSHOT.jar
      Handler: bonsonzheng.url.shortener.LambdaFunctionUrlShortner::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active